[package]
name = "editor-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ropey = "1.6.1"
color-eyre = "0.6.2"
crossterm = "0.27.0"
ratatui = { version = "0.24.0", features = ["all-widgets"] }
